import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/global.css"
import Verticlebar from "@/components/verticlebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </head>
      <body className={inter.className}>
        {children}
        <Verticlebar/>
      </body>
    </html>
  );
}
